### ISSUE TITLE
webpack 4.5 produces warning about Tapable.plugin is deprecated

### ISSUE THREAD

**Issue by bigfish** [alexpalombaro/modernizr-webpack-plugin#26]
using 1.0.7 of this plugin, I get this warning in build output 

`
 10% building modules 3/3 modules 0 active(node:86959) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at ModernizrPlugin.apply (/Volumes/devhd/dev/securityportal/sp-client/node_modules/modernizr-webpack-plugin/index.js:105:12)
    at webpack (/Volumes/devhd/dev/securityportal/sp-client/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Volumes/devhd/dev/securityportal/sp-client/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:16)
    at processOptions (/Volumes/devhd/dev/securityportal/sp-client/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
    at Object.<anonymous> (/Volumes/devhd/dev/securityportal/sp-client/node_modules/webpack-dev-server/bin/webpack-dev-server.js:504:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`

**Comment by ezmiller** [comment]
I'm also seeing this. When I ran `node --trace-deprecation ./node_modules/webpack-cli/bin/webpack.js`, I got:

```
(node:55735) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at ModernizrPlugin.apply (/Users/ethan/Projects/motologic/enzo/client/node_modules/modernizr-webpack-plugin/index.js:105:12)
    at webpack (/Users/ethan/Projects/motologic/enzo/client/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Users/ethan/Projects/motologic/enzo/client/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse.err (/Users/ethan/Projects/motologic/enzo/client/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/ethan/Projects/motologic/enzo/client/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/ethan/Projects/motologic/enzo/client/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/ethan/Projects/motologic/enzo/client/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by andrew-luminal** [comment]
Also seeing this, would love to get it removed.

**Comment by sergeymorkovkin** [comment]
Confirm.

**Comment by chriswburke** [comment]
I feel like the issue is coming from 'html-webpack-plugin'

**Comment by lebdimaa** [comment]
![capture](https://user-images.githubusercontent.com/22050677/44342398-85fe8d80-a493-11e8-8d31-82da1a223974.PNG)

**Comment by neutraali** [comment]
![modernizr-webpack-plugin](https://user-images.githubusercontent.com/16540190/45479441-2f613800-b74f-11e8-93a4-48ffce4de8fc.png)
**Confirmed** - Is this project still alive?
